/**
 * Renders the extracted design system as a DESIGN.md document — the
 * getdesign.md-style convention: an LLM/human-readable summary of the
 * project's colors, typography, spacing, radii, shadows and motion tokens.
 */
import type { DesignSystemReport, DesignToken, TokenCategory } from '../core/types';

export interface DesignMdMeta {
  projectName: string;
  toolVersion: string;
  generatedAt: string;
}

type ReportData = Omit<DesignSystemReport, 'markdown'>;

const SECTION: Array<{ title: string; categories: TokenCategory[]; blurb: string }> = [
  { title: 'Colors', categories: ['color', 'gradient'], blurb: 'Color tokens as authored (CSS custom properties / Tailwind theme).' },
  { title: 'Typography', categories: ['font', 'font-size', 'font-weight'], blurb: 'Font families and the type scale.' },
  { title: 'Spacing', categories: ['spacing'], blurb: 'Spacing / sizing scale.' },
  { title: 'Border Radius', categories: ['radius'], blurb: 'Corner radii, smallest to largest.' },
  { title: 'Shadows', categories: ['shadow'], blurb: 'Elevation and shadow styles.' },
  { title: 'Motion', categories: ['motion'], blurb: 'Durations and easing curves.' },
  { title: 'Breakpoints', categories: ['breakpoint'], blurb: 'Responsive breakpoints.' },
  { title: 'Z-Index', categories: ['z-index'], blurb: 'Stacking order scale.' },
  { title: 'Other Tokens', categories: ['other'], blurb: 'Tokens that did not fit a category above.' },
];

const esc = (s: string) => s.replace(/\|/g, '\\|');
const code = (s: string) => `\`${s.replace(/`/g, "'")}\``;

export function renderDesignMarkdown(report: ReportData, meta: DesignMdMeta): string {
  const out: string[] = [];
  const themeNames = report.themes.map((t) => t.name).filter((n) => n !== 'base');

  out.push(`# DESIGN.md — ${meta.projectName}`);
  out.push('');
  out.push(
    `> Auto-generated by Atlas v${meta.toolVersion} on ${meta.generatedAt.slice(0, 10)}. ` +
      `Extracted from ${report.sources.length} source file${report.sources.length === 1 ? '' : 's'}. ` +
      `Do not edit by hand — re-run \`atlas analyze\` to refresh.`,
  );
  out.push('');

  // ---- Overview -----------------------------------------------------------
  out.push('## Overview');
  out.push('');
  out.push(`| | |`);
  out.push(`| --- | --- |`);
  out.push(`| Design tokens | ${report.counts.total} |`);
  out.push(`| Colors | ${report.counts.colors} |`);
  out.push(`| Font families | ${report.counts.fonts} |`);
  out.push(`| Spacing tokens | ${report.counts.spacing} |`);
  out.push(`| Radii | ${report.counts.radii} |`);
  out.push(`| Shadows | ${report.counts.shadows} |`);
  out.push(`| Themes | ${report.themes.map((t) => t.name).join(', ') || '—'} |`);
  out.push('');

  if (report.themes.length) {
    out.push('### Themes');
    out.push('');
    out.push('| Theme | Scope | Declarations |');
    out.push('| --- | --- | --- |');
    for (const t of report.themes) {
      out.push(`| ${t.name} | ${code(t.selector)} | ${t.tokenCount} |`);
    }
    out.push('');
  }

  // ---- Font families ------------------------------------------------------
  if (report.fonts.length) {
    out.push('## Font Families');
    out.push('');
    out.push('| Family | Role | Stack |');
    out.push('| --- | --- | --- |');
    for (const f of report.fonts) {
      out.push(`| **${esc(f.family)}** | ${f.role} | ${code(esc(f.stack))} |`);
    }
    out.push('');
  }

  // ---- Token sections ------------------------------------------------------
  for (const section of SECTION) {
    const tokens = report.tokens.filter((t) => section.categories.includes(t.category));
    if (!tokens.length) continue;

    out.push(`## ${section.title}`);
    out.push('');
    out.push(section.blurb);
    out.push('');

    // Only add theme columns where at least one token in the section overrides.
    const overriding = themeNames.filter((name) =>
      tokens.some((t) => t.themeValues && name in t.themeValues),
    );
    out.push(`| Token | Value${overriding.map((n) => ` | ${n}`).join('')} |`);
    out.push(`| --- | ---${overriding.map(() => ' | ---').join('')} |`);
    for (const t of tokens) {
      const cells = overriding.map((n) => {
        const v = t.themeValues?.[n];
        return v ? code(esc(v)) : '—';
      });
      out.push(
        `| ${code(t.name)} | ${code(esc(t.value))}${cells.map((c) => ` | ${c}`).join('')} |`,
      );
    }
    out.push('');
  }

  // ---- Literal palette (what's actually painted on screen) ----------------
  if (report.literalColors.length) {
    out.push('## Palette In Use');
    out.push('');
    out.push('Literal color values found in stylesheet declarations, by frequency.');
    out.push('');
    out.push('| Color | Occurrences |');
    out.push('| --- | --- |');
    for (const c of report.literalColors.slice(0, 16)) {
      out.push(`| ${code(c.value)} | ${c.count} |`);
    }
    out.push('');
  }

  // ---- Usage ---------------------------------------------------------------
  const example = pickExample(report.tokens);
  if (example) {
    out.push('## Usage');
    out.push('');
    out.push('Reference tokens through their custom properties so themes cascade:');
    out.push('');
    out.push('```css');
    out.push('.my-component {');
    for (const t of example) out.push(`  ${propertyFor(t)}: var(${t.name});`);
    out.push('}');
    out.push('```');
    out.push('');
  }

  if (report.sources.length) {
    out.push('## Sources');
    out.push('');
    for (const s of report.sources) out.push(`- ${code(s)}`);
    out.push('');
  }

  return out.join('\n');
}

/** Pick up to three representative CSS-variable tokens for the usage example. */
function pickExample(tokens: DesignToken[]): DesignToken[] | null {
  const vars = tokens.filter((t) => t.name.startsWith('--'));
  if (!vars.length) return null;
  const pick = (c: TokenCategory) => vars.find((t) => t.category === c);
  return [pick('color'), pick('radius'), pick('shadow'), pick('spacing')]
    .filter((t): t is DesignToken => Boolean(t))
    .slice(0, 3);
}

function propertyFor(t: DesignToken): string {
  switch (t.category) {
    case 'color':
      return 'color';
    case 'radius':
      return 'border-radius';
    case 'shadow':
      return 'box-shadow';
    case 'spacing':
      return 'padding';
    case 'font':
      return 'font-family';
    case 'font-size':
      return 'font-size';
    default:
      return 'value';
  }
}
